# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.26)
{


  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };


  outputs = { self, flake-schemas, nixpkgs }:
    let

      supportedSystems = [ "x86_64-linux" "aarch64-darwin" "x86_64-darwin" "aarch64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {

      schemas = flake-schemas.schemas;


      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {

          packages = with pkgs; [
            curl
            git
            jq
            wget
            nixpkgs-fmt
          ];
        };
      });

      # Hello World package
      packages = forEachSupportedSystem ({ pkgs }: {
        hello-world = pkgs.writeShellScriptBin "hello-world" ''
          echo "Hello World from NixOS GitLab Runner!"
          echo "System: $(uname -a)"
          echo "Nix version: $(nix --version)"
          echo "Current time: $(date)"
        '';
      });
    };
}
