# ============================================
# GitLab Runner Registration
# ============================================
# Automatically creates and registers a runner in GitLab
# Users don't need to manually create the runner in GitLab UI

resource "gitlab_user_runner" "nixos_runner" {
  runner_type = "project_type"
  project_id  = var.gitlab_project_id

  description = var.gitlab_runner_description
  tag_list    = var.gitlab_runner_tags
  untagged    = var.gitlab_runner_untagged
}

# Local to use the generated token in runner configuration
locals {
  # Use the token generated by GitLab provider
  runner_token = gitlab_user_runner.nixos_runner.token
}

